-- Jalankan SQL ini di Supabase SQL Editor (https://supabase.com/dashboard/project/_/sql/new)
-- setelah bikin project baru.

CREATE TABLE IF NOT EXISTS mobil (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nama TEXT NOT NULL,
  kategori TEXT,
  harga INTEGER,
  transmisi TEXT,
  kapasitas INTEGER,
  mesin TEXT,
  foto TEXT,
  warna TEXT,
  fitur TEXT,
  deskripsi TEXT,
  tipe TEXT,
  sort_order INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS promo (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  judul TEXT,
  deskripsi TEXT,
  diskon TEXT,
  kode TEXT,
  gambar TEXT,
  validUntil TEXT,
  warna TEXT,
  sort_order INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS testimoni (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nama TEXT,
  rating INTEGER,
  komentar TEXT,
  foto TEXT,
  mobil TEXT,
  tanggal TEXT,
  sort_order INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS berita (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  judul TEXT,
  kategori TEXT,
  tanggal TEXT,
  gambar TEXT,
  excerpt TEXT,
  sort_order INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS gallery (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  judul TEXT,
  kategori TEXT,
  gambar TEXT,
  sort_order INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS keunggulan (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  icon TEXT,
  title TEXT,
  desc TEXT,
  sort_order INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  key TEXT UNIQUE NOT NULL,
  value TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  nama TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS test_drive (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nama TEXT NOT NULL,
  nohp TEXT NOT NULL,
  mobil TEXT NOT NULL,
  tanggal TEXT NOT NULL,
  lokasi TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS trade_in (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nama TEXT NOT NULL,
  nohp TEXT NOT NULL,
  merek TEXT NOT NULL,
  tahun TEXT NOT NULL,
  kilometer TEXT NOT NULL,
  kondisi TEXT NOT NULL,
  mobil_target TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);
